### ISSUE TITLE
:bulb: Improve code (Caching).

### ISSUE THREAD

**Issue by rohankumawat** [rohankumawat/spotifyStreamlit#10]
### Idea Contribution

- [X] I have read and agree to follow this project's [Code of Conduct](https://github.com/rohankumawat/spotifyStreamlit/blob/main/CODE_OF_CONDUCT.md).

### Tell us about your idea.

Streamlit has updated their code for caching. 
- [x] Change the cache function in the Spotify.py file.

**Comment by Coderbeep** [comment]
@rohankumawat Can I take this one?

**Comment by rohankumawat** [comment]
> @rohankumawat Can I take this one?

Hey! Yes. You can take it.
